### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by MartinStyk** [xstefank/pv243-music-library#1]
- [x] Aplikace bude plně zabezpečena, bude používat minimálně tři úrovně oprávnění
- [x]  Datový model bude anotovaný pomocí Bean Validation
- [x]  Aplikace bude testovatelná (Arquillian)
- [x] Aplikace bude nasazena v clusteru dvou uzlů v doménové konfiguraci, přiložen konfigurační skript (JBoss CLI) a demonstrována její odolnost vůči výpadku jednoho z nich (lze simulovat na jednom počítači)
- [x] Aplikace bude vystavovat rozhraní pro komunikaci mezi systémy (JAX-RS) - formát zpráv JSON
- [x] Aplikace bude používat alespoň jeden WebSocket endopint
- [x] Aplikace bude volat alespoń jeden REST endpoint
- [x] Vystavené endpointy budou podoporovat zabezpečení
- [x] Aplikace bude obsahovat alespoň jeden use case pro použití Concurrency nebo Batching API
- [x] Aplikace bude obsahovat alespoň jeden use case pro použití JMS 2.0 API
